### ISSUE TITLE
Try to start a CUDA Working Group

### ISSUE THREAD

**Issue by gnzlbg** [rust-cuda/wg#1]
## Motivation

There are a bunch of people (5-10 AFAICT) using Rust+CUDA through the NVPTX backend. Even though we all use different approaches to this, there are some things that all approaches have in common: we all have to use the Rust NVPTX backend which is not as great as we'd love to, we all have to use CUDA intrinsics, test things, compile / link / load kernels, etc. 

It would already be a big step forward if we had a place were we could talk with each other, and ideally organize some common work that would be useful for all current frameworks and approaches. So that's the initial and currently only goal I have.

## Initial goal

EDIT: the initial goals discussion is now happening here: #4 

* Find out who wants to be involved in this working group ?

> That is, find out who is using / trying to use Rust+CUDA, and get everyone to agree on a communication channel. I'll ping some people below, feel free to ping others.

* Choose a communication channel that suits the majority of those who want to be involved:

Then we can set up the communication channel so that we have a place were we can talk with each other about solving fundamental toolchain issues. 

## Communication channels

EDIT: We have settled on using Zulip for the time being. If you like to chat with us, drop by: https://rust-cuda.zulipchat.com/ and say hi!

### Github 

I've set up a github organization and a working group repo, so we could communicate exclusively through here. 

### Chat / Interactive

I think it also makes sense to have some interactive form of communication available. 

There are official rust-lang organizations in IRC, Discord, Zulip, and probably others. 

#### Zulip

I personally prefer Zulip (we use it for the unsafe-code-guidelines-wg), because it allows the chat discussions to be organized hierarchically into "streams", so that if 2 groups of people are talking simultaneously about two different topics, these conversations do not mix, and can be easily tracked.

### Discourse forum

`rust-embedded` has a tag in the official rust forums, so maybe we could ask for one> 

### Other communication channels

Are there any other communication channels that we should be considering?

# Why not GPGPU Working Group ?

Independently of how the general Rus+GPGPUs problem is solved, Rust+CUDA is a problem worth solving.

Trying to come up with a general GPGPU abstraction that wraps CUDA, OpenCL, Vulkan, OpenMP, OpenACC, Sycl, HPX, HSA, ... is a tough problem, particularly when most things are not really working. 

Rust+CUDA is available today and it kind of works, and I think there are people who are mainly interested in using Rust with nVidia GPUs. Improving the situation for these users does not preclude solving the more general GPGPU problem in the future.

# Members

I've tried to ping some people that I know are using CUDA+Rust or have done so in the past. Please feel free to ping others. 

About me - I work on computational fluid dynamics, and maintain some low-level Rust library APIs (libc, stdsimd, jemallocator, ...) and tools (`cargo-asm`, `cargo-llvm-ir`). I use CUDA through C++, but would like at some point to be easily able to use it from Rust in production, and my first step was to expose the NVPTX intrinsics via `core::arch` a while ago. Ideally, one day, we would all be able to use CUDA+stable Rust, with a robust toolchain that always works.

# List of participants

EDIT: If you'd like to join, send a PR adding yourself to the list!

Here is a list of people interested in participating and their preferred communication channels

* @gnzlbg -> preferably zulip, but whatever suits most people would be good too,
* @denzp -> 
* @bheisler -> preferably slack/discord, but zulip could work too,
* @vadixidav 
* @termoshtt

**Comment by gnzlbg** [comment]
cc @japaric, @bheisler, @denzp, @DiamondLovesYou, @BoisterousCoder ,  @Seeker14491 , @vadixidav , @antoinewdg, @termoshtt,  @k0nserv , @king6cong

**Comment by kpp** [comment]
Last time I tried to use NVPTX on my Linux machine crashed the whole system. Because you all know the famous video: https://www.youtube.com/watch?v=_36yNWw_07g

On the other side I managed to run `accel` and it worked quite well. Although I am not a CUDA dev, I was hired to add Vec based on `Managed Memory`. And that's all.

Did you invite me because of https://github.com/rust-accel/accel/pull/50 ?

**Comment by gnzlbg** [comment]
> Did you invite me because of rust-accel/accel#50 ?

Yes.

**Comment by denzp** [comment]
I'll be happy join the WG, and I think it's a great idea to centralize our efforts! Thanks for organising this!

I'd like to add one more possible communication channel - Discourse. It doesn't replace interactive chat platforms, but can be used alongside with Github organization for strategic planning and discussion. But in the end, it could be that Github alone is enough for this purpose. Does somebody have experience using Discourse?

About myself - I'm not an actual CUDA developer, more like a CUDA hobbyist. And I'm trying to achieve seamless and easy CUDA development workflow since May 2017 (when I started to write a [CUDA tutorial](https://github.com/denzp/rust-inline-cuda-tutorial)).

**Comment by denzp** [comment]
cc @hobofan due to CUDA experience and remarkable work on [Leaf](https://github.com/autumnai/leaf).

**Comment by gnzlbg** [comment]
> I'd like to add one more possible communication channel - Discourse.

This is a great idea; i've added it to the top post. IIRC (@japaric might correct me) the `rust-embeded` working group gained a `rust-embedded` tag in the official rust-lang forums (which use DIscourse), so we could ask for this as well, and the benefit would be that we don't have to set anything up, and that all Rust users can easily interact with this working group when they feel like it.

**Comment by hobofan** [comment]
Sorry, but I haven't really worked with CUDA since the work on Leaf ended, and my priorities lie elsewhere now.

What I can do is transfer the crates/crate names (`cublas`,`cublas-sys`,`cudnn`,`cudnn-sys`) to this WG, if you want to. No other crates currently depend on them and I feel like the names are too good to be wasted on unmaintaned crates.

Best of luck!

**Comment by bheisler** [comment]
Oh, fantastic! I'm glad someone else took the lead on this - I was going to do it myself if nobody else did. Count me in.

I think we should expand the scope to GPGPU in general. Nothing says that we have to build an abstraction over all the various flavors of GPGPU, and having one place to go for GPGPU-related contributions would be good. I agree we should focus our efforts on CUDA to start with, but we shouldn't exclude those who want to work on Vulkan or OpenCL. Also, if we make a working group for just CUDA, then we have to either rename it or make another one for GPGPU later on.

Since we're talking about ourselves, I've been experimenting with GPU-accelerating some software at work, but the nature of that experimentation probably shouldn't be posted on the public internet yet. I've been pushing to use Rust for the host-side code if/when we turn those experiments into a product. It'd be nice if we could use Rust for the device code as well.

In my copious spare time over the last month, I've been working on a Rust-y wrapper for the CUDA Driver API. It's still very much a work-in-progress - so much so that I haven't posted it to GitHub yet - but I'm pretty happy with how it's turning out.

EDIT: Regarding communication channels, I'd rather not have to set up yet another chat app, so I'd prefer Slack or Discord if possible, but if we go with Zulip I can deal. Discourse would be good as well.

**Comment by gnzlbg** [comment]
>  I think we should expand the scope to GPGPU in general. Nothing says that we have to build an abstraction over all the various flavors of GPGPU, and having one place to go for GPGPU-related contributions would be good. I agree we should focus our efforts on CUDA to start with, but we shouldn't exclude those who want to work on Vulkan or OpenCL. Also, if we make a working group for just CUDA, then we have to either rename it or make another one for GPGPU later on.

So I actually thought about this quite a bit. 

I avoided calling this "GPGPU Working Group" because I did not want this to attract people saying we should pursue SPIR-V instead or OpenCL or ... and derailing the discussions into that direction. 

My primary goal is to get people that are currently using and working with and on the Rust NVPTX backend to talk to each other so that we can maybe work together on common fundamental problems like "the last LLVM upgrade broke the NVPTX backend",  "the core::arch broke on nightly", etc. For this reason, I intended to call this the "CUDA Working Group", although maybe we should call it the  "NVPTX Working Group" instead.  

These problems are shared by all Rust CUDA frameworks, so even though the approaches of accel, ptx-builder, and @japaric's libraries is different, we would all benefit from collaborating on cross-framework toolchain issues.

Also, some working groups, like the embedded working group, have sub-working groups. If a more general "GPGPU Working Group" is started, we would probably just become a sub-group of it.

**Comment by cathalgarvey** [comment]
Hi folks, I want no part in assisting proprietary, monopolistic stacks of nonfree software.

I'll mute this henceforth but I hope ye can redirect your efforts to something standard and liberating, instead of helping NVidia continue to lock down deep learning and GPU compute, for free.

On 11 November 2018 14:58:33 GMT+00:00, gnzlbg <notifications@github.com> wrote:
>>  I think we should expand the scope to GPGPU in general. Nothing says
>that we have to build an abstraction over all the various flavors of
>GPGPU, and having one place to go for GPGPU-related contributions would
>be good. I agree we should focus our efforts on CUDA to start with, but
>we shouldn't exclude those who want to work on Vulkan or OpenCL. Also,
>if we make a working group for just CUDA, then we have to either rename
>it or make another one for GPGPU later on.
>
>So I actually thought about this quite a bit. 
>
>My primary goal is to get people that are currently using and working
>with and on the Rust NVPTX backend to talk to each other so that we can
>maybe work together on common fundamental problems. For this reason, I
>intended to call this the "CUDA Working Group" (although we could
>rename this to NVPTX if desired"). 
>
>By fundamental problems I did not meant to suggest creating a new CUDA
>framework for Rust: Accel's approach is different from ptx-builder and
>different from @japaric's approach and this is fine. What I meant is
>solving problems like "the last LLVM upgrade broke the NVPTX backend", 
>"the core::arch broke on nightly", etc. With the initial objectives of
>trying to move NVPTX to a tier 2 target that we can rely on when
>building our own frameworks. Maybe, once we start talking / working
>together, we decide to build a framework together, but even if that is
>not the case, we can still benefit from working together on issues that
>affect all frameworks.
>
>I avoided calling this "GPGPU Working Group" because I did not want
>this to attract people saying we should pursue SPIR-V instead or OpenCL
>or ... and derailing the discussions into that direction. We are using
>CUDA, we all have to deal with some common problems from time to time,
>let's start by working together on those. 
>
>Some working groups, like the embedded working group, have sub-working
>groups. So I'd guess that if someone kickstarts a more general "GPGPU
>Working Group" we would just become a sub-group of that one - but even
>if that were to happen, having a place for people working specifically
>on CUDA would make sense.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-cuda/wg/issues/1#issuecomment-437677057

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kpp** [comment]
> Hi folks, I want no part in assisting proprietary, monopolistic stacks of nonfree software.

@cathalgarvey I am a newbie. What exactly is proprietary?

**Comment by gnzlbg** [comment]
I'm going to pro-actively moderate the thread to prevent the discussion from derailing. If you need to discuss the pros/cons of supporting CUDA I beg you to do so somewhere else.

**Comment by vadixidav** [comment]
I am interested in contributing in some way, though my current experience with LLVM and in the rust compiler's code is somewhat lacking. I have worked with CUDA before, but never PTX itself directly. If I can contribute to this in some way, I am interested in helping take this to the next stage. My primary motivation is creating a native machine learning and GPU parallelization framework. Technically we could do this without Rust -> PTX, but it would be greatly assisted by doing this.

If it is possible to use reversal of concerns and combinators to build a GPU pipeline (via traits and generics), and possibly even derive the gradient calculations for machine learning algorithms built in this way, it would already be much farther than other things out there that have a fixed CUDA kernel to solve these pipelines dynamically (like TensorFlow). I am very interested in the prospect of allowing the combination of generics and deriving CUDA kernel implementations for generic functions in this way. This probably wont be an immediate concern, but it might be something we can write an RFC for further down the line, and I would like to make sure that the way we do this doesn't preclude that possibility in the future.

**Comment by vadixidav** [comment]
At least initially I think we should try and figure out how to utilize the work already done to allow it to be used in upstream Rust in a way that allows these future extensions.

**Comment by bheisler** [comment]
> My primary goal is to get people that are currently using and working with and on the Rust NVPTX backend to talk to each other so that we can maybe work together on common fundamental problems like "the last LLVM upgrade broke the NVPTX backend", "the core::arch broke on nightly", etc. For this reason, I intended to call this the "CUDA Working Group", although maybe we should call it the "NVPTX Working Group" instead.

Fair enough. In that case, I think we should at least include the CUDA-related `-sys` crate(s) under the umbrella of the working group, since those would be shared between different libraries. The existing `cuda-sys` crate is good enough for now, but it does have some flaws:

* Only exposes one specific version (8.0) of the CUDA API's. Any crate that wants to use newer features (or any crate that wants to be compatible with older versions of CUDA) is currently out of luck.
* Combines driver, runtime and cublas in a single crate. cublas should definitely be a separate crate, and arguably driver & runtime as well.
* It would be nice if it automatically searched common locations for the CUDA libraries like `openssl-sys` does.

That doesn't need to hold up work on the NVPTX backend though.

**Comment by vadixidav** [comment]
My nomination is in favor of communicating on Discord, but not due to technical reasons, just that I primarily use it. There is a Rust programming language discord for working groups already as well, but I am not opposed to using other forms of communication.

**Comment by termoshtt** [comment]
Hi, thanks for orginaizing this WG!

> The existing cuda-sys crate is good enough for now, but it does have some flaws:

These points are reasonable. I am willing to move `cuda-sys` crate from rust-accel/accel to under this wg, or hand over the "cuda-sys" name on crates.io to new crate. It has been created from CUDA/C headers using bindgen, but I've made some modification for managing.

**Comment by gnzlbg** [comment]
cc @dylan-dpc

**Comment by Dylan-DPC-zz** [comment]
Hi

I am willing to help even though I don't have a need to use CUDA right now.
 Over the last few months, I have used both discord & zulip and both have its pros & cons. 

Discord is popular and easier for newcomers to start with, but given that after sometime discussions are most likely to branch to different topics, I prefer Zulip because the threaded model fits well for this usecase. Though Zulip app (on android) isn't up to the mark, it has improved a lot in the latest release

**Comment by DiamondLovesYou** [comment]
Hi all,

I would be very interested in joining/starting such a group, though my interest is in accelerator devices in general, not specifically in CUDA. I've never used zulip, but I'm not opposed it; I use slack and discord already though.

I have actually been working on this for a while. I have gotten Rust kernels (single source code, no less) running on an AMDGPU RX 580. A zoom-able fractal generating kernel, which I've used to generate animations from. My plan is to turn this into a product, which is why I haven't released it yet.

There is a lot missing from Rust to be able to fully utilize GPUs, from/with any of SPIRV, AMDGPU, or NVPTX. For example, to support GPU texture and buffer types one needs to do specific things in LLVM IR to signal that such hardware features are desired (at the kernel level): SPIRV uses specially named opaque LLVM types which are passed around using pointers along with argument metadata attached to kernels, AMDGPU uses `inreg` vectors of specific size (images themselves use `<i32 x 4>`, samplers of images use `<i32 x 8>`) (though this is only for *shaders*, not general compute), NVPTX/NVVM uses "annotations" (basically metadata key/value pairs) on global variables/arguments. For OpenCL C w/ AMDGCN, sampler and image types are passed as pointers, which are cast to `__constant uint8*` or `__constant uint4*`, loaded and then that load is passed to whatever intrinsic. Plus some intrinsics (on AMDGPU at least) return pointers which are in specific address spaces, which currently isn't expressible in platform specific intrinsic spec files.

On top of this there are actually two concerns here: distributed memory and distributed processing (of course, we're mostly talking about Von Neumann architectures, but for most practical purposes instruction and data memories are separate, despite both being members of a machine's unified/flat address space). Regarding distributed memory, we have more work. There are different levels of support for this: unified (as in, pointer values are the same for two different processors) and disjoint. For either we need a way for types to report internal allocations, as the memory of a value of the type doesn't include any indication otherwise, but would certainly fault if accessed remotely.

Plus QOL improvements to Rust, mostly in the form of ignorable attributes: some form of loop unrolling would be a great start.

**Comment by gnzlbg** [comment]
@DiamondLovesYou that sounds awesome, feel free to drop by zulip and say hi, and send a PR to the repo adding yourself to the members list :)

**Comment by gnzlbg** [comment]
So it seems that we have started already :)
