### ISSUE TITLE
Collect roadmap ideas

### ISSUE THREAD

**Issue by gnzlbg** [rust-cuda/wg#4]
Before making an announcement about the working group, we should have an idea about what's our Roadmap. I'd like to collect some ideas for this, so that we at some point can have a discussion and choose a roadmap.

**Comment by gnzlbg** [comment]
We haven't really worked much together, so I think our initial roadmap should be focused on a single small goal. There are many many things we might want to achieve, e.g., missing features like static/dynamic arrays in kernels, have a great single source compilation model, etc. But these all look like very complex and long term goals for me. 

So I think we should focus on what are the easiest and quickest things to fix / problems to solve that deliver the most value to those using NVPTX / CUDA from Rust.

## Initial goal: make `nvptx` a Tier-2 target

**Goal**: make `nvptx` a tier 2 rust target (with some asteriks maybe, but less asterisks than what we have now). That is, cross-compiling to `nvptx` should always work at least from the x86_64 tier 1 targets. 

I think having this kind of support upstreamed in rustc would be increadibly valuable, since it would mean that LLVM upgrades cannot break our frameworks and applications. This goal is not very small. To achieve this goal I've come up with two main objectives: 

* Objective 1: fix rustc and prevent it from breaking anything again
   * solve code generation problems
   * solve linking problems
   * add proper nvptx targets to rustc (e.g. initially only 64-bit ones)
   * add tests to rustc: codegen tests, compilation, linking, etc. - no run tests, but we need to validate ptx output

* Objective 2: make sure fundamental libraries (e.g. `libcore`) work properly in `nvptx` kernels and continue doing so: 
   * **nvptx intrinsics** (e.g. `syncthreads`): these are already exposed via `core::arch::nvptx`, but their implementation, which lives in `stdsimd`, is not really tested at all.  
  * `libc`: some kernel operations like `memcpy` might belong in `libc`. In any case, `extern crate libc;` should not make compilation fail in `nvptx` kernels, even if that means that `libc` must be effectively empty
  * `libm`: `libcore` math operations are partly exposed via `libcore`, and partly only in `libstd` via `libm`. We should make sure that calling, e.g., math functions like `f32::sin` works in kernels, and maybe figure out how to expose the approximative math functions as well
  * `cuda-sys `: bindings for host-side code should always compile, and generate the appropriate code
  * To achieve all this we will probably have to come up with ways to test things in the platforms that the rust-lang/rust organization uses: Travis-CI, appveyor, etc. We will have to create proper Docker images for the nvptx target, maybe wrappers to validate the generated ptx code, etc. 

I think that would already be enough work for an initial goal that would make all our lives much much easier. What do you think?

## Future goals
       
I think that future goals could include further small steps to improve the situation for everybody, e.g., implement missing nvptx features like static/dynamic arrays in kernels, maybe an allocator crate to easily allocate/deallocate/manage the different types of memory available, etc.

**Comment by bheisler** [comment]
Overall, this plan sounds good to me. I do have a few comments though:

>         * make and test that `libc` compiles for `nvptx` "as is"
>         * make and test that `stdsimd` compiles for `nvptx` "as is"
>         * make and test that `cuda-sys` compiles for `nvptx` "as is"

There may be a misunderstanding here. The NVPTX backend compiles Rust code into kernel code. Unlike with `nvcc`, it is not (or at least not currently) possible to include host and device code in the same crate. Since kernel code cannot call `libc` or `cuda-sys` functions, it doesn't make sense to compile those with NVTPX. I'm not sure about `stdsimd`, but that's probably host-only as well.

If we want to mix host and device code together, the way to do that is to have a procedural attribute macro that copies tagged code to a temporary crate, compiles it to PTX and then includes it into the host crate. This is effectively what `nvcc` (and Accel) do already.

>         * e.g. provide base docker containers to use in CI system like travis, appveyor, etc.
>           to build nvptx targets, build the tools needed to validate the ptx output, etc.

It might help to be more clear about the goal here. We could create an image with the tools necessary to compile Rust code to PTX. Unfortunately, none of the usual cloud-CI providers (Travis-CI, AppVeyor or CircleCI) provide GPU-equipped build VMs so we wouldn't be able to run the resulting kernels.

I think we'll mostly have to go without CI unless someone volunteers to set up and maintain a public Jenkins server with a CUDA-capable GPU.

> maybe an allocator crate to easily allocate/deallocate/manage the different types of memory available, etc.

Correct me if I'm wrong, but I believe that Rust currently only supports global allocators - that is, every Box and Vec uses the same allocator. I don't think that would be desirable for CUDA - even programs that use Unified memory wouldn't want all of their heap allocations to be shared with the device. If we could have local allocators (eg. `Box<T, Allocator=Unified>` or similar) that could work for unified and page-locked memory, but I don't expect those to be stabilized any time soon.

**Comment by gnzlbg** [comment]
> There may be a misunderstanding here. The NVPTX backend compiles Rust code into kernel code. Unlike with nvcc, it is not (or at least not currently) possible to include host and device code in the same crate. Since kernel code cannot call libc or cuda-sys functions, it doesn't make sense to compile those with NVTPX. I'm not sure about stdsimd, but that's probably host-only as well.

I think there has been a misunderstanding! I wasn’t suggesting single source compilation!

Some functions, like `memcpy`, or the math functions, are available in kernel code, and `libc` and `libm` typically export these. Other functions, like `syncthreads`, are currently exposed in `core::arch::nvptx`, whose implementation is the `stdsimd` crate (the `stdsimd` is literally imported into `libcore`). 

So what I was suggesting is that these fundamental libraries should be importable from kernel code without compilation errors exposing whatever APIs make sense for kernels (and are tested etc.). This might mean that `libc` must be empty, but if that's the case then so be it. What shouldn't be the case is that they contain some host code that fails to compile weirdly when a new user tries to include them from kernel code.

Does that make sense? 

> Correct me if I'm wrong, but I believe that Rust currently only supports global allocators - that is, every Box and Vec uses the same allocator. I don't think that would be desirable for CUDA

Is it possible to dynamically allocate memory from CUDA kernels? I recall reading that this was possible, but I've never used. In any case, the allocator issue was a "food for future thought" kind of thing. For Host code, Allocators for Box and Vec are nightly only, and currently a WIP. We could try to see if we can have some impact here, but there are currently more pressing problems.

**Comment by bheisler** [comment]
Ah, I see what you mean now. Yes, that makes sense. Do you envision kernel crates would import libc/libm/etc. directly? I had expected that there would be a dedicated kernel-core crate that exposed those functions, but I don't really have a solid reason for that.

> Is it possible to dynamically allocate memory from CUDA kernels? I recall reading that this was possible, but I've never used.

Ah, again I'd misunderstood. I thought you were talking about exposing `cudaMalloc`/`cudaFree` and friends as a host-side allocator.

It is possible to dynamically allocate memory in kernels, yes. I can't say for sure but I don't think it's very common. Even so, It would be nice if the standard Box/Vec/etc. types could Just Work in kernels.

Forgive me, I've been immersed in the driver API for a month now so I'm mostly thinking in host-side terms.

**Comment by gnzlbg** [comment]
> Do you envision kernel crates would import libc/libm/etc. directly?

I am not sure. I guess this is my fault for making the objective too specific. I should rephrase it as "getting the most fundamental libraries of the kernel ecosystem (`libcore` and similar) working properly, and tested, so that they do not break inadvertently". Where exactly do we put the relevant stuff, and how, is kind of up to us to decide. We don't have to decide it now or here, we can open specific issues to have more focused discussions on this topic, and maybe try to meet once on the chat to discuss this interactively and try to find an approach that makes sense for all of us.

EDIT: I've updated my proposed second objective to make what I meant clearer.

> It is possible to dynamically allocate memory in kernels, yes. I can't say for sure but I don't think it's very common. Even so, It would be nice if the standard Box/Vec/etc. types could Just Work in kernels.

Solving this problem is a really nice goal, thank you! For kernels that do not resize, reallocate, etc. slices are probably enough, but it would significantly simplify memory management in the host side if we could just write: `Vec<T, HostAlloc>`, `Vec<T, DeviceAlloc>`, `Vec<T, HostDeviceAlloc>`, etc. So thumbs up on this!

**Comment by bheisler** [comment]
> > It is possible to dynamically allocate memory in kernels, yes. I can't say for sure but I don't think it's very common. Even so, It would be nice if the standard Box/Vec/etc. types could Just Work in kernels.
> 
> Solving this problem is a really nice goal, thank you! For kernels that do not resize, reallocate, etc. slices are probably enough, but it would significantly simplify memory management in the host side if we could just write: `Vec<T, HostAlloc>`, `Vec<T, DeviceAlloc>`, `Vec<T, HostDeviceAlloc>`, etc. So thumbs up on this!

Well, let's not go too far. Memory allocated within a kernel is not accessible to the host (even through the usual `cudaMemcpy`/`cudaMemset`/etc. functions). What I meant was that it would be nice if a kernel could create and free Boxes and Vecs internally - they would have to be dropped at the end of the kernel. That could be done with a global allocator, though naturally it would only affect the kernel crate.

I don't think it's possible to have a host-side `Vec<T, DeviceAlloc>` - device memory is not directly accessible by the host, so it would segfault as soon as you tried to read or write the elements of the Vec. A host-side `Vec<T, UnifiedAlloc>` might be possible, but would probably be unsafe - what happens if it reallocates while a kernel is running?

**Comment by denzp** [comment]
> add tests to rustc: codegen tests, compilation, linking, etc. - no run tests, but we need to validate ptx output

I believe we can accomplish this with `ptxas` tool from CUDA toolchain. I'm afraid it can't guarantee the correctness of the PTX assembly, but at least it can warn about rough syntax problems. It's being used in `ptx-linker` [tests](https://github.com/denzp/rust-ptx-linker/blob/master/tests/steps/verification.rs), but only if it is installed on the host machine. Unfortunately, it is currently not a case with Travis, because of environment setup times, but if we prepare a Docker image with all the needed tools we can run the tests on a daily basis.

If we going to provide better guarantees on the PTX assembly quality and correctness, we should think how we can solve the problem with testing on a real hardware. And I think I have an idea about this! 

What do you think about having an *"Observer"* service that keeps track of Nightly releases and several *"Workers"* that can run tests and examples on a real hardware. 
The *Observer* will provide an information about the state of CUDA with current nightly / beta / stable, and probably even some historical data. 

As for the *Worker* node, there can be any PC or laptop, compatible to run CUDA, and they should poll the *Observer* to check if there is a pending Rust release to verify tests with. I could provide my machine as one of the workers, because my GPU is idling quite often, and hopefully it wouldn't affect the host system much.

How sane (or insane) does this sound? :wink:

**Comment by gnzlbg** [comment]
> How sane (or insane) does this sound?

[OSU](https://osuosl.org/services/powerdev/) offers access to a PowerPC Linux cluster with nvidia GPUs for free for open source project testing. We considered applying for this to test the Rust powerpc backends, the `core::arch::powerpc` intrinsics, and maybe upgrading powerpc to a tier 1 target. Testing the NVPTX backend would be another reason to apply for access.

An alternative would be to get some Amazon Elastic Compute nodes with nvidia GPUs for testing.There are a couple of ways to set these up on Github as CI, and depending on how much capacity we need per month, it might be "free".

**Comment by denzp** [comment]
Oh, that would be nice!

---

As for the Amazon Elastic Compute, I researched the most popular GPU computing solutions but didn't find chances to use "open source discount" or any other quota. As far as I understood even GCE's "$300 entry credit" can't be applied to GPU instances...

It's always possible to spin up and teardown GPU instances on demand during CI job and run tests on an actual hardware, but it will only reduce costs, not eliminate it completely.

**Comment by termoshtt** [comment]
> fix rustc and prevent it from breaking anything again

It's really important :sweat:

> solve linking problems

In my understanding, we can set a target-dependent linker in rustc like [ARM target switch its default linker into lld](https://users.rust-lang.org/t/psa-cortex-m-breakage-lld-as-the-default-linker/19890) (though this had been reverted). Do we focus to use rust-ptx-linker to default linker? This may enable us to drop xargo dependence and give better cargo support.

> I believe we can accomplish this with ptxas tool from CUDA toolchain.

I use `nvcc --cubin` in nvidia/cuda container to validate PTX output by compiling into .cubin since it can be used without GPU. I had used GitLab CI with a runner on my private desktop in the early stage of accel since my desktop works when I push to repository.
